describe('Your Band Sucks', () => {
    it('Displays correctly', () => {
        cy.visit('/')
        cy.get('h1 span').contains('YOUR').should('exist')
        cy.get('h1 span').contains('BAND').should('exist')
        cy.get('h1 span').contains('S').should('exist')
        cy.get('h1 span').contains('U').should('exist')
        cy.get('h1 span').contains('CKS').should('exist')
        cy.get('a').contains('Log In').should('exist').click()
        cy.get('#input_2').type('colemanimhoff@gmail.com')
        cy.get('#input_3').type('YorkPA84')
        cy.get('.user-form div.row button').eq(0).click()
        cy.get('a').contains('Home').should('exist').click()
        cy.get('img.album').eq(0).click()
        cy.get('.modal-footer button').eq(0).click()
        cy.get('a').contains('About').should('exist').click()
        cy.get('a').contains('Profile').should('exist').click()
        cy.get('a').contains('Log Out').should('exist').click()
    })
})